import NavBar from "@/components/NavBar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Search } from "@/components/ui/search";
import { UserNav } from "@/components/userNav";

const inter = Inter({ subsets: ["latin"] });

export const dynamic = 'force-dynamic'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex justify-between w-screen h-16 items-center border-b px-12">
          <NavBar />
          <div className="ml-auto flex items-center space-x-4">
            <div className="hidden md:flex">
              <Search />
            </div>
            <UserNav />
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
